[tool.cibuildwheel]
skip = ["cp36-*", "pp*", "pypy*", "*musllinux*"]

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

[tool.cibuildwheel.linux]
archs = ["x86_64"]

[build-system]
requires = ["setuptools", "wheel", "Cython"]
