[project]
name = "coffe"
version = "3.0.0"
description = "Python wrapper for the COrrelation Function Full-sky Estimator code"
readme = "README.md"
requires-python = ">=3.7"
authors = [
    {name = "Goran Jelic-Cizmek", email = "goran.jelic-cizmek@unige.ch"},
]
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved",
    "Programming Language :: Cython",
    "Programming Language :: C",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Physics",
]
dependencies = [
    "numpy>=1.19.5",
]
optional-dependencies.test = ["pytest", "pandas", "scipy"]

[project.scripts]
coffe-cli = "coffe.__main__:main"

[project.urls]
repository = "https://github.com/JCGoran/coffe"

[tool.cibuildwheel]
skip = ["cp36-*", "pp*", "pypy*", "*musllinux*"]
test-extras = ["test"]
test-command = ["pytest {package}/tests"]

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

[tool.cibuildwheel.linux]
archs = ["x86_64"]

[build-system]
requires = ["setuptools", "wheel", "Cython<3"]
