name: build-docs

# Only run this when the master branch changes
on:
  pull_request:
  push:
    branches:
    - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python3 -m pip install .[docs]

    # Build the site
    - name: Build the site
      run: |
        bash scripts/generate_docs.sh

    # If we've pushed to master, push the book's HTML to github-pages
    - if: ${{ github.ref == 'refs/heads/master' }}
      name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
